# Generated by Django 5.0.1 on 2024-01-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg_board_app', '0004_alter_advertisement_image1_and_more'),
    ]

    operations = [
    ]
